### PR TITLE
dkms: ::worr-exheres -> ::arbor

### PR DESCRIPTION
**Pull request by tgurr**
Since there are quite a few packages supporting dkms now I think it makes sense to have this very useful tool available directly in ::arbor.

### CODE REVIEW

**Comment by tgurr** [comment]
GitLab merge request for ::arbor: https://gitlab.exherbo.org/exherbo/arbor/merge_requests/487

**Comment by worr** [comment]
Yeah, that works for me. That's probably for the best since I haven't been active in the Exherbo community recently. I'll merge once I've seen that the exheres has been merged in arbor.

**Comment by Keruspe** [comment]
@worr done

**Comment by worr** [comment]
All set! Thanks so much!

**Pull request merged**
